version: '3'
services:
  react:
    build:
      context: .
      dockerfile: Dockerfile # docker-compose build で Dockerfile を使ってビルドする。
    command: sh -c "npm start" # docker-compose up でサーバーを立ち上げる。
    ports:
     - "3000:3000"
    tty: true